version: "3"
networks:
  backend:
    driver: bridge
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    networks:
      - backend
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    networks:
      - backend
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LOG_RETENTION_HOURS=1
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_COMPRESSION_TYPE=snappy
      - KAFKA_CFG_MAX_MESSAGE_BYTES=50
      - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
    depends_on:
      - zookeeper
  algorithm-service:
    build:
      context: ./algorithm-service
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - kafka
